#!/bin/bash
code --install-extension abusaidm.html-snippets
code --install-extension akamud.vscode-theme-onedark
code --install-extension atlassian.atlascode
code --install-extension bibhasdn.django-html
code --install-extension castwide.solargraph
code --install-extension codepunkt.vscode-javascript-snippets
code --install-extension CraigMaslowski.erb
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension doublefint.pgsql
code --install-extension dzannotti.vscode-babel-coloring
code --install-extension ecmel.vscode-html-css
code --install-extension esbenp.prettier-vscode
code --install-extension flowtype.flow-for-vscode
code --install-extension kisstkondoros.csstriggers
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension lsadam0.ReactFlowSnippets
code --install-extension mkaufman.HTMLHint
code --install-extension mohsen1.prettify-json
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-mssql.mssql
code --install-extension ms-python.python
code --install-extension ms-vscode.atom-keybindings
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension octref.vetur
code --install-extension PKief.material-icon-theme
code --install-extension rebornix.ruby
code --install-extension redhat.vscode-yaml
code --install-extension RoscoP.ActiveFileInStatusBar
code --install-extension sdras.night-owl
code --install-extension shinnn.stylelint
code --install-extension sleistner.vscode-fileutils
code --install-extension TimonVS.ReactSnippetsStandard
code --install-extension toasty-technologies.octave
code --install-extension vincaslt.highlight-matching-tag
code --install-extension vortizhe.simple-ruby-erb
code --install-extension vscodevim.vim
code --install-extension waderyan.gitblame
code --install-extension wayou.vscode-todo-highlight
code --install-extension wix.vscode-import-cost
code --install-extension xabikos.ReactSnippets
code --install-extension ZneuRay.erb-vscode-snippets
